### ISSUE TITLE
[TOPIC] - Cluster

### ISSUE THREAD

**Issue by deviantony** [portainer/kubernetes-beta#13]
Have some feedback about the cluster related features? Discuss it here.

**Comment by tomasz-zylka-fluke** [comment]
Hi team!
Great job :)
Have a question about cluster view - would that be possible to show additionally disc space usage?

**Comment by deviantony** [comment]
@tomasz-zylka-fluke we'll keep in mind for future evolutions around the cluster features but AFAIK there is no way to get this information through the Kubernetes API. Maybe with the metrics-server enabled.

**Comment by deviantony** [comment]
A user reported that it would have been interested to see the public IP of the node in the node list. They reported that this information was available if a [CCM](https://kubernetes.io/docs/concepts/architecture/cloud-controller/) was available and returning this information.

Example of YAML information available:

```yaml
addresses:
 - address: scw-foo-wizardly-torvalds-18bdf335272645aba33f
   type: Hostname
 - address: 10.9.172.115
   type: InternalIP
 - address: e58cc88f-1a74-40d2-b934-6dc4db8b711e.domain.com
   type: InternalDNS
 - address: 143.112.126.221
   type: ExternalIP
 - address: e58cc88f-1a74-40d2-b934-6dc4db8b711e.pub.domain.com
   type: ExternalDNS
```
