### ISSUE TITLE
[TOPIC] - k3s

### ISSUE THREAD

**Issue by deviantony** [portainer/kubernetes-beta#6]
We have not tested the deployment of the Portainer for Kubernetes BETA version in k3s.

Have any feedback about deploying and using the Portainer for Kubernetes BETA version in k3s? 

Discuss it here.

**Comment by WhiteBahamut** [comment]
Just did it today on my RasPi4. Followed https://github.com/portainer/portainer-k8s and changed the image tag.
Had to use legacy ip tables for k3s. Load Balancer sample worked for me, did not tried Node Port.

**Comment by wesselah** [comment]
I did the same on raspberry pi 4 and also needed legacy ip tables . I am not fluid on kubernetes but where do you store the persistant data or do we need to use configmap because when removing portainer we need to enter credentials again and changes are not saved also

**Comment by WhiteBahamut** [comment]
same problem for me. Not sure if this is a portainer or k3s issue. I start k3s with the `--default-local-storage-path [path]` option. But this was not respected by k3s or portainer.
My workaround is to update the config map as the first step after k3s setup with `kubectyl apply -f local-volume.yaml`

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: kube-system
data:
  config.json: |-
        {
                "nodePathMap":[
                {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths":["/path/to/local/folder"]
                }
                ]
        }
```

still, after reboot of the whole host I get the default vaule for local-path-config. But it seems in the background my updated value is used

**Comment by WhiteBahamut** [comment]
Added an ubuntu worker node to my k3s master. Works as expected. See it in portainer and apps are scaled (if set)

**Comment by deviantony** [comment]
@wesselah @WhiteBahamut the current manifests for Portainer do not persist the data associated to Portainer (mainly because it depends on the storage provider / storage classes available in your cluster).

If you want to persist the data, you'll have to manually update the manifests to persist the `/data` container folder.

**Comment by WhiteBahamut** [comment]
I know, so I extended the manifest to persist `/data`.
k3s comes with a local-path provider by default. Yet it seems to "forget" changes made to the local-path-config. I assume this is a k3s problem, and portainer is not messing around with the local-path-config configmap.

**Comment by WhiteBahamut** [comment]
Just to follow up.
Installing k3s with this command `curl -sfL https://get.k3s.io | sh -s - server --default-local-storage-path [your storage path]` seems to work for me and k3s remembers the default path after reboot (I want to store the data somewhere else, and not the default path).

Adding a PVC for portainer 
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-pvc
  namespace: portainer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
```

and using it
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: portainer
spec:
  selector:
    matchLabels:
      app: app-portainer
  template:
    metadata:
      labels:
        app: app-portainer
    spec:
      serviceAccountName: portainer-sa-clusteradmin
      containers:
      - name: portainer
        image: portainer/portainer-k8s-beta:linux-arm
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: portainer-pvc
```

If you **remove** portainer, and its PVC it will lose its data ofcourse.

**Comment by deviantony** [comment]
Thanks for the update @WhiteBahamut

**Comment by wesselah** [comment]
@WhiteBahamut : does the same apply to the agent command when installing or only on the server?

**Comment by WhiteBahamut** [comment]
I am not a k3s expert, but as far as I understand the path provided to `--default-local-storage-path` must be available on all cluster nodes. On the agent you dont need to configure it again (also no option for it).
In my quick tests services which had a local-path pvc pointing to a folder not present on the node failed to start up.

**Comment by wesselah** [comment]
Okee i will test with a nfs share and see what happens

**Comment by deviantony** [comment]
@WhiteBahamut @wesselah it's ok for you to discuss in this issue, it was made for that :-)

All of your feedback is welcome !

**Comment by wesselah** [comment]
@WhiteBahamut do i need to declare a pv first because the pvc status keeps pending with your example

**Comment by wesselah** [comment]
my fault it was pending because nothing was claiming it now it is bound and portainer is working on the nfs share

**Comment by WhiteBahamut** [comment]
yeha, might took a tiny bit.
I extendet the portainer xaml to include the pvc:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: portainer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-pvc
  namespace: portainer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: portainer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer-sa-clusteradmin
  namespace: portainer
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: portainer-crb-clusteradmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: portainer-sa-clusteradmin
  namespace: portainer
---
apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
spec:
  type: LoadBalancer
  selector:
    app: app-portainer
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: portainer
spec:
  selector:
    matchLabels:
      app: app-portainer
  template:
    metadata:
      labels:
        app: app-portainer
    spec:
      serviceAccountName: portainer-sa-clusteradmin
      containers:
      - name: portainer
        image: portainer/portainer-k8s-beta:linux-arm
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: portainer-pvc
```

It ditched the edge part, as I dont use it. I think **1Gi** is too much, but this can be adjusted as you like. Never checked how much portainer actually consumes in my setups. Should only be some MB.
